Add variable
cheestick/filmoteka pull request #7
Opened 2022-05-04 14:04 UTC by Tkachmaxim

Добавлены имена переменных, подключен сброс стилей, подключен шрифт, добавлен контейнер

2022-05-04 14:10 UTC, cheestick commented
@Tkachmaxim пулриквест нужно на dev ветку создать ( не на main)

2022-05-04 15:21 UTC, cheestick requested changes

2022-05-04 15:21 UTC, cheestick commented on src/sass/main.scss
> +@import './utils/_reset';
По требованиям :

2. Подключен modern-normalize

2022-05-04 15:21 UTC, cheestick commented on src/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
Во всем проекте используется только Roboto 500?

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +.visually-hidden {
Вынеси в отдельный файл aux-effects.aces

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +.hoover {
В aux-effect.scss

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +    &:hover {
Второй раз в коде: используй плейсхолдер scss

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +img {
В aux-effect.scss

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +img {
В aux-effect.scss

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +    &:hover {
Scss placeholder rule

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +// Сброс стилей
После подключения modern normalize оставь то что нужно в ресет, что не относится к ресету в другой файл по примеру aux-effects.scss

2022-05-04 15:21 UTC, cheestick commented on src/sass/utils/_reset.scss
> +// Сброс стилей
После подключения modern normalize оставь то что нужно в ресет, что не относится к ресету в другой файл по примеру aux-effects.scss

2022-05-04 18:12 UTC, Tkachmaxim commented
все сделад, единственное добавилось в package.json modern-normalize

2022-05-04 19:21 UTC, cheestick commented on src/sass/main.scss
> +@import '../../node_modules/modern-normalize/modern-normalize.css';
../../node_modules -это, по идее, лишняя часть пути

2022-05-04 19:27 UTC, cheestick requested changes

2022-05-04 19:27 UTC, cheestick commented on src/sass/utils/_aux-effects.scss
> +    transition-timing-function: $cubic;
это код повторяется в строках 35-37 именно его нужно вынести как placeholder

2022-05-04 19:27 UTC, cheestick commented on src/sass/utils/_aux-effects.scss
> +        transition-timing-function: $cubic;
комментарий в строках 8-10

2022-05-05 07:16 UTC, cheestick approved these changes
heal the deal.

2022-05-05 07:16 UTC, merged